# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      development_minor:
        dependency-type: development
        update-types:
          - minor
          - patch
      development_major:
        dependency-type: development
        update-types:
          - major
      production_minor:
        dependency-type: production
        update-types:
          - minor
          - patch
      production_major:
        dependency-type: production
        update-types:
          - major

