name: 'Dependabot Batcher: Scheduled'
on:
  schedule:
    - cron: '0 9 * * 1,3'

jobs:
  # Batches Dependabot PRs into one by merging them into a combined branch, then raising a new PR
  dependabot-batcher:
    name: 'Combine Dependabot PRs'
    uses: 'Legal-and-General/dependabot-batcher@v1.0.2'
    with:
      token: ${{ secrets.YOUR_TOKEN }} #required
      baseBranchName: 'main' #optional
      batchBranchName: 'dep-batcher-updates' #optional
      batchPullTitle: 'Dependabot Batcher Updates' #optional
